import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#0071e8",
        "on-secondary": "#ffffff",
        "surface-tint": "#c00100",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-surface": "#2b1613",
        "surface-variant": "#ffdad4",
        "surface-container-low": "#fff0ee",
        "on-surface-variant": "#603e39",
        error: "#ba1a1a",
        secondary: "#575e70",
        "on-tertiary-container": "#fefcff",
        "on-primary-fixed": "#410000",
        "inverse-surface": "#422a27",
        tertiary: "#0059ba",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#acc7ff",
        "surface-container": "#ffe9e6",
        "surface-container-highest": "#ffdad4",
        "tertiary-fixed": "#d7e2ff",
        "secondary-fixed-dim": "#c0c6db",
        outline: "#956d67",
        "surface-bright": "#fff8f6",
        primary: "#bc0100",
        "secondary-container": "#d9dff5",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container-high": "#ffe2dd",
        "primary-container": "#eb0000",
        "on-tertiary-fixed-variant": "#004491",
        surface: "#fff8f6",
        "primary-fixed": "#ffdad4",
        "inverse-primary": "#ffb4a8",
        "on-primary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ffedea",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        "on-tertiary-fixed": "#001a40",
        "on-background": "#2b1613",
        "secondary-fixed": "#dce2f7",
        "on-secondary-container": "#5c6274",
        "on-primary-fixed-variant": "#930100",
        background: "#fff8f6",
        "outline-variant": "#ebbbb4",
        "surface-dim": "#f8d1cb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        xl: "80px",
        md: "24px",
        base: "4px",
        xs: "8px",
        lg: "48px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        caption: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        button: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-md": ["30px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        button: ["16px", { lineHeight: "1", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
